/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExamplesResourceManagerRouteImport } from './routes/examples/resource-manager'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamplesResourceManagerRoute = ExamplesResourceManagerRouteImport.update({
  id: '/examples/resource-manager',
  path: '/examples/resource-manager',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/examples/resource-manager': typeof ExamplesResourceManagerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/examples/resource-manager': typeof ExamplesResourceManagerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/examples/resource-manager': typeof ExamplesResourceManagerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/examples/resource-manager'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/examples/resource-manager'
  id: '__root__' | '/' | '/examples/resource-manager'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExamplesResourceManagerRoute: typeof ExamplesResourceManagerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/examples/resource-manager': {
      id: '/examples/resource-manager'
      path: '/examples/resource-manager'
      fullPath: '/examples/resource-manager'
      preLoaderRoute: typeof ExamplesResourceManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExamplesResourceManagerRoute: ExamplesResourceManagerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
